x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  backend: {}

services:
  postgres:
    cap_drop:
      - ALL
    deploy:
      !!merge <<: *common-deploy
    environment:
      !!merge <<: *common-env
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "$N8N_DB_PASSWORD"
      POSTGRES_USER: "postgres"
    healthcheck:
      interval: 5s
      retries: 3
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "$N8N_DB_PASSWORD"]
      timeout: 60s
    image: postgres:17
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    volumes:
      - $STORAGE_PATH/n8n/database:/var/lib/postgresql/data