x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  backend: {}

services:
  postgres:
    cap_drop:
      - ALL
    deploy:
      !!merge <<: *common-deploy
    environment:
      !!merge <<: *common-env
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "$N8N_DB_PASSWORD"
      POSTGRES_USER: "postgres"
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "$N8N_DB_PASSWORD"]
      timeout: 5s
    image: postgres:18.1@sha256:5ec39c188013123927f30a006987c6b0e20f3ef2b54b140dfa96dac6844d883f
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    tmpfs:
      # For read-only filesystem, need to create a volume/tmpfs for PostgreSQL to run its much
      # needed configuration. The read-only flag does not make volumes and tmpfs read-only.
      - /var/run/postgresql:rw,uid=1000,gid=1000
    user: "1000:1000"
    volumes:
      - $STORAGE_PATH/n8n/database:/var/lib/postgresql